#!/bin/sh

### Set the wallpaper

feh --bg-max Pictures/wallpaper.png


# rescale monitor

# xrandr --output SCREEN --scale VALUE --filter nearest

### Set the keyboard layout us and ch. You can toggle by super + space

setxkbmap -model pc104 -layout us,ch -variant fr -option grp:win_space_toggle


### Excecute each file in etc directory
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


### Start i3 window manager
exec i3
