" File: ~/.vimrc

" PLUG-IN
  source $HOME/.vim/plug.vimrc
  source $HOME/.vim/plug-config.vimrc

" personnal information
  source $HOME/.vim/personnal-info.vimrc

" main settings
  source $HOME/.vim/settings.vimrc
